# Generated by Django 5.2.5 on 2025-08-12 23:34

import autologx.api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('engine_repair', 'Engine Repair'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_mileage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('attachment_type', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice'), ('photo', 'Photo'), ('warranty', 'Warranty'), ('manual', 'Manual'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=autologx.api.models.attachment_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.servicerecord')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('trim', models.CharField(blank=True, max_length=50)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('engine_size', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-Automatic'), ('other', 'Other')], max_length=20)),
                ('oil_viscosity', models.CharField(blank=True, help_text='e.g., 0W-20, 5W-30', max_length=10)),
                ('current_mileage', models.IntegerField(default=0)),
                ('last_oil_change_mileage', models.IntegerField(blank=True, null=True)),
                ('last_oil_change_date', models.DateField(blank=True, null=True)),
                ('last_service_mileage', models.IntegerField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('stock_tire_size', models.CharField(blank=True, max_length=30)),
                ('stock_wheel_size', models.CharField(blank=True, max_length=20)),
                ('current_tire_size', models.CharField(blank=True, max_length=30)),
                ('current_wheel_size', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='api.vehicle'),
        ),
    ]
